# Generated by Django 3.2.9 on 2022-08-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statement',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
