# Generated by Django 3.2.9 on 2022-08-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_auto_20220824_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='highlighted',
        ),
    ]
