# Generated by Django 3.2.9 on 2022-10-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0006_alter_file_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
