# syntax=docker/dockerfile:1
FROM python:3.9
ENV PYTHONUNBUFFERED=1


ARG DJANGO_ALLOWED_HOSTS
ARG DJANGO_SECRET_KEY
ARG DJANGO_CORS_ORIGIN_WHITELIST

ENV DJANGO_ALLOWED_HOSTS $DJANGO_ALLOWED_HOSTS
ENV DJANGO_SECRET_KEY $DJANGO_SECRET_KEY
ENV DJANGO_CORS_ORIGIN_WHITELIST $DJANGO_CORS_ORIGIN_WHITELIST


WORKDIR /code
COPY requirements.txt /code/
EXPOSE 4200
RUN pip install -r requirements.txt
COPY . /code/