import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState, useEffect, ChangeEvent } from "react";

const Home: NextPage = () => {
  // File state
  const [message, setMessage] = useState("");

  

  // Get all files
  const getAPIResponse = async () => {
    const res = await axios
      .get("http://localhost:4200/example/example/")
      .then((res) => {
        console.log(res.data);
        setMessage(res.data);
      });
  };

  // On mount get files
  useEffect(() => {
    getAPIResponse();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>Message from API</h3>
        <p>{message?.message}</p>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
